fix(og-card) hide footer and header when there's no content
orgenic/orgenic-ui pull request #116
Opened 2020-01-09 08:55 UTC by demkani

# Pull Request

## Type of change

Please delete any option that is not relevant.

- [ ] New feature (a non-breaking change)
- [ ] Breaking change
- [x] Bug fix (a non-breaking change which fixes an issue - please add the issue reference in the description section)
- [ ] Other (a non-breaking change - please add details in the description section)

## Description

Fixes issue where header (incl. spacing) was still visible, even without content or title. 

Fixes #40 #99 

## Checklist

- [x] Local build is still running with my changes
- [ ] I added tests 
- [ ] New and existing unit test pass locally with my changes
- [x] My changes do not contain any dead or commented out code
- [ ] I added documentation for public functionality
- [ ] I added comments, at least in hard-to-understand areas

2020-01-17 09:43 UTC, Cr45hCode requested changes

2020-01-17 09:43 UTC, Cr45hCode commented on src/components/og-card/og-card.tsx
> +    return slot ? true : false;
```suggestion
    return slot !== null;
```

2020-01-23 09:00 UTC, jfu-maximago approved these changes

2020-01-23 10:39 UTC, Cr45hCode approved these changes

2020-01-23 10:39 UTC, merged